// LevelSelection/data.js
export const levels = [
    {
      id: "a1",
      name: "A1",
      title: "Beginner",
      description: "Basic communication, simple daily phrases",
      progress: 25,
      color: "#3b82f6",
      icon: "🔤",
    },
    {
      id: "a2",
      name: "A2",
      title: "Elementary",
      description: "Simple expressions, everyday conversations",
      progress: 0,
      color: "#8b5cf6",
      icon: "💬",
    },
    {
      id: "b1",
      name: "B1",
      title: "Intermediate",
      description: "Clear communication on familiar matters",
      progress: 0,
      color: "#10b981",
      icon: "📝",
    },
    {
      id: "b2",
      name: "B2",
      title: "Upper Intermediate",
      description: "Complex communication, technical discussions",
      progress: 0,
      color: "#f59e0b",
      icon: "🗣️",
    },
    {
      id: "c1",
      name: "C1",
      title: "Advanced",
      description: "Fluent expression, complicated subject matter",
      progress: 0,
      color: "#ef4444",
      icon: "📚",
    },
    {
      id: "c2",
      name: "C2",
      title: "Proficiency",
      description: "Near-native proficiency, mastery of complex language",
      progress: 0,
      color: "#6366f1",
      icon: "🎓",
    },
  ];